language: node_js
node_js:
  - "11.0"
cache: 
  yarn: true
  directories:
    - node_modules
    - .firebase
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng build --prod
after_success:
  - firebase deploy --token $FIREBASE_TOKEN