language: node_js
node_js:
  - "14.17"
cache: 
  npm: true
  directories:
    - node_modules
    - .firebase
branches:
  only:
    - master
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - ng build --prod
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
notifications:
  email:
    recipients:
      - $OWNER_EMAIL
    on_success: always
    on_failure: always